// <auto-generated />
namespace HSNHospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changedatatypeforsalaryinjobpost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedatatypeforsalaryinjobpost));
        
        string IMigrationMetadata.Id
        {
            get { return "202004102035561_Change-datatype-for-salary-in-jobpost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
